unpackaged/objects/Mix__c.object
<CustomObject>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Song__c.object
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Mix__c</fullName>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{0000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/TrackTriggerHandler.cls
public class TrackTriggerHandler implements TriggerTemplate.Handler {
  
    private List<Track__c> newValues = null;
    private Map<Id, Track__c> oldValues = null;
    
    public void setValues(List<sObject> newValues, Map<Id, sObject> oldValues)
    {
        this.newValues = (List<Track__c>)newValues;
        this.oldValues = (Map<Id, Track__c>)oldValues;
    }
    
    public void handle(TriggerTemplate.TriggerAction action)
    {
        if ((action == TriggerTemplate.TriggerAction.beforeInsert)||
            (action == TriggerTemplate.TriggerAction.beforeUpdate))
        {
            List<Track__c> tracksToCheck = new List<Track__c>();
            for (Track__c t : newValues)
                if (t.Song__c != null)
                    tracksToCheck.add(t);
            TrackService.validateTracksNumberAndLength(tracksToCheck);
        }
        if (action == TriggerTemplate.TriggerAction.afterUndelete)
        {
            TrackService.validateTracksNumberAndLength(newValues);
            TrackService.doTracksCountChange(newValues);
            TrackService.doCalculateGenreFrequency(newValues);
        }
        if (action == TriggerTemplate.TriggerAction.afterInsert)
        {
             TrackService.doTracksCountChange(newValues);
             TrackService.doCalculateGenreFrequency(newValues);  
        }
        if (action == TriggerTemplate.TriggerAction.afterUpdate)
        {
          // Process only tracks with new Song__c value 
            List<Track__c> tracks = new List<Track__c>();
            for(Track__c t: newValues)
            {
               if(t.Song__c!= oldValues.get(t.Id).Song__c || t.Mix__c != oldValues.get(t.Id).Mix__c)
               {
                   tracks.add(t);
                   tracks.add(oldValues.get(t.Id));
               }
            }
            TrackService.doTracksCountChange(tracks);
            TrackService.doCalculateGenreFrequency(tracks);
        }
        if (action == TriggerTemplate.TriggerAction.afterDelete)
        {            
            TrackService.doTracksCountChange(oldValues.values());
            TrackService.doCalculateGenreFrequency(oldValues.values());/*oldValues.values()*/
        }       
    }
}