unpackaged/objects/Mix__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mixes</relationshipLabel>
        <relationshipName>Mixes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alternative Music</fullName>
                </value>
                <value>
                    <fullName>Blues</fullName>
                </value>
                <value>
                    <fullName>Classical Music</fullName>
                </value>
                <value>
                    <fullName>Country Music</fullName>
                </value>
                <value>
                    <fullName>Dance Music</fullName>
                </value>
                <value>
                    <fullName>Easy Listening</fullName>
                </value>
                <value>
                    <fullName>Electronic Music</fullName>
                </value>
                <value>
                    <fullName>Hip Hop / Rap</fullName>
                </value>
                <value>
                    <fullName>Indie Pop</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin Music</fullName>
                </value>
                <value>
                    <fullName>New Age</fullName>
                </value>
                <value>
                    <fullName>Opera</fullName>
                </value>
                <value>
                    <fullName>Pop (Popular Music)</fullName>
                </value>
                <value>
                    <fullName>R&amp;B / Soul</fullName>
                </value>
                <value>
                    <fullName>Reggae</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>World Music / Beats</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_m__c</fullName>
        <label>Length (m)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Mix__c</fullName>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{0000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/MixController_Test.cls
@isTest
public class MixController_Test {

    private static Integer TOTAL_GENRES_NUMBER = 19;
    private static Mix__c mix;
    private static PageReference ref;
    private static MixController ctrl;
    private static Integer totalTracks = 0;
    private static Double totalLength = 0.0;

    @testSetup static void setup()
    {
        TestDataFactory.initializeTest();
    }

    @isTest static void testPassContactInUrl()
    {
        Contact c = [SELECT Id FROM Contact].get(0);
        PageReference reference = new PageReference('/apex/NewMixPage?contactId='+c.Id);
        Test.setCurrentPage(reference);
        MixController controller = new MixController();
        System.assertEquals(c.Id, controller.mix.Customer__c);
    }

    @isTest static void testNewMixPageInitialization()
    {
        PageReference reference = new PageReference('/apex/NewMixPage');
        Test.setCurrentPage(reference);
        MixController controller = new MixController();

        System.assertEquals(19, controller.getGenres().size());
        System.assertEquals([SELECT Count(Id) cnt FROM Song__c].get(0).get('cnt'), controller.setCon.getResultSize());
        System.assertEquals(19, controller.getGenres().size());
        System.assertEquals(2, controller.totalPages);
        System.assertEquals(1, controller.pageNumber);
    }

    @isTest static void testFilterByGenre()
    {
        PageReference reference = new PageReference('/apex/NewMixPage');
        Test.setCurrentPage(reference);
        MixController controller = new MixController();
        String randomGenre = [SELECT Genre__c FROM Song__c].
            get((Integer)Math.mod( Math.round(Math.random() * 1000), MixController.RECORDS_PER_PAGE)).Genre__c;
        controller.genreToShow = randomGenre;
        controller.filterByGenre();
        for(MixController.SongWrapper s : controller.getSong())
            System.assertEquals(randomGenre, s.song.Genre__c);

        controller.genreToShow = '--Any Genre--';
        controller.filterByGenre();
        System.assertEquals(MixController.RECORDS_PER_PAGE, controller.getSong().size());
    }

    @isTest static void testExistingMixEditPageInitialization()
    {
        List<Song__c> generatedSongs = initMix();

        System.assertEquals(mix.Name, ctrl.mix.Name);
        System.assertEquals(mix.Customer__c, ctrl.mix.Customer__c);
        for (Song__c s : generatedSongs)
            System.assert(ctrl.selectedSongs.containsKey(s.Id));

    }

    @isTest static void testPagination()
    {
        List<Song__c> generatedSongs = initMix();
        ctrl.firstPage();
        checkWrapping(true);
        ctrl.lastPage();
        checkWrapping(false);
        ctrl.previousPage();
        checkWrapping(true);
        ctrl.nextPage();
        checkWrapping(false);
    }

    @isTest static void testCancelCommand()
    {
        initMix();
        // API Id has 18 characters, UI Id has 15 characters
        System.assert(('/' + mix.Id).startsWith(ctrl.cancel().getUrl()));
    }

    @isTest static void testSaveCommand()
    {
        PageReference reference = new PageReference('/apex/NewMixPage');
        Test.setCurrentPage(reference);
        MixController controller = new MixController();
        controller.mix.Name = 'newTestMix';
        controller.mix.Customer__c = [SELECT Id FROM Contact].get(0).Id;
        Integer songNumberToGenerate = (Integer)Math.mod( Math.round( Math.random() * 1000 ), MixController.RECORDS_PER_PAGE);
        List<Song__c> songs = [SELECT Id FROM Song__c];
        for (Integer i = 0; i < songNumberToGenerate; i++ )
            controller.selectedSongs.put(songs.get(i).Id , songs.get(i));
        controller.save();

        System.assertEquals(songNumberToGenerate, [SELECT Id FROM Track__c ].size());

    }

    private static List<Song__c> initMix()
    {
        mix = [SELECT Id, Name, Customer__c FROM Mix__c].
        get((Integer)Math.mod( Math.round( Math.random() * 1000 ), TestDataFactory.TEST_MIXES_COUNT));
        TestDataFactory.fillMixWithDifferentSongs(mix);
        ref = new PageReference('/apex/NewMixPage?id='+mix.Id);
        Test.setCurrentPage(ref);
        ctrl = new MixController();

        List<Song__c> generatedSongs = [SELECT Id, Length_m__c FROM Song__c WHERE Id IN (SELECT Song__c FROM Track__c WHERE Mix__c = :mix.Id)];
        for (Song__c s : generatedSongs) 
        {
            totalTracks++;
            totalLength += s.Length_m__c;
        }
        return generatedSongs;

    }

    private static void checkWrapping(Boolean firstPage)
    {
        List<Song__c> songs = firstPage ? [SELECT Id FROM Song__c LIMIT :MixController.RECORDS_PER_PAGE] :
                              [SELECT Id FROM Song__c  OFFSET 10];
        Integer i = 0;
        for (Song__c s : songs)
            System.assertEquals(s.Id, ctrl.getSong().get(i++).song.Id);
    }


}