unpackaged/objects/Mix__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mixes</relationshipLabel>
        <relationshipName>Mixes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryGenre__c</fullName>
        <label>Primary Genre</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondaryGenre__c</fullName>
        <label>Secondary Genre</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Artist__c</fullName>
        <label>Artist</label>
        <length>180</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alternative Music</fullName>
                </value>
                <value>
                    <fullName>Blues</fullName>
                </value>
                <value>
                    <fullName>Classical Music</fullName>
                </value>
                <value>
                    <fullName>Country Music</fullName>
                </value>
                <value>
                    <fullName>Dance Music</fullName>
                </value>
                <value>
                    <fullName>Easy Listening</fullName>
                </value>
                <value>
                    <fullName>Electronic Music</fullName>
                </value>
                <value>
                    <fullName>Hip Hop / Rap</fullName>
                </value>
                <value>
                    <fullName>Indie Pop</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin Music</fullName>
                </value>
                <value>
                    <fullName>New Age</fullName>
                </value>
                <value>
                    <fullName>Opera</fullName>
                </value>
                <value>
                    <fullName>Pop (Popular Music)</fullName>
                </value>
                <value>
                    <fullName>R&amp;B / Soul</fullName>
                </value>
                <value>
                    <fullName>Reggae</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>World Music / Beats</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_m__c</fullName>
        <label>Length (m)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Licenses__c</fullName>
        <label>Track Licenses</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Mix__c</fullName>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <displayFormat>TRACK-{0000}</displayFormat>
        <label>Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/TestDataFactory.cls
@isTest
public class TestDataFactory{

	public static final Integer TEST_MIXES_COUNT = 5;
	public static final Integer MAX_TRACKS_COUNT = 15;
	public static final Integer TEST_SONG_NUMBER = 18;
	public static final Integer MAX_TRACK_COUNT = 20;
	public static final Integer MAX_MIX_LENGTH = 90;

	public static Mix__c getRandomMix()
	{
		return [SELECT Id, Name, PrimaryGenre__c, SecondaryGenre__c FROM Mix__c].get((Integer)Math.mod(Math.round(Math.random()*1000), TEST_MIXES_COUNT));
	}

	public static void initializeTest()
	{
		Contact testContact = new Contact(LastName = 'testContacts');
		insert testContact;
		List<Mix__c> mixes = new List<Mix__c>();
		for (Integer i = 0; i < TEST_MIXES_COUNT; i++)
			mixes.add(new Mix__c(Name='testMix'+i,Customer__c = testContact.Id,PrimaryGenre__c='',SecondaryGenre__c=''));
		insert mixes;
		List<sObject> ls = Test.loadData(Song__c.sObjectType, 'testSongs');
	}

	public static Mix__c getRandomMix(Mix__c mix)
	{
		Mix__c anotherMix;
		do
		{
			anotherMix = getRandomMix();
		}
		while (mix.Id == anotherMix.Id);
		return anotherMix;
	}

	public static List<Track__c> createRelatedTracks(Mix__c mix, Boolean oneSong)
	{
		List<Track__c> tracks = new List<Track__c>();
		List<Song__c> availableSongs = [SELECT Id, Genre__c,Track_Licenses__c FROM Song__c];
		for (Integer i = 0; i < (oneSong ? availableSongs.get(0).Track_Licenses__c : TEST_SONG_NUMBER);i++)
			tracks.add(new Track__c(Mix__c = mix.Id, Song__c = availableSongs.get(oneSong ? 0 : i).Id));
		insert tracks;
		return tracks;
	}

	public static List<Track__c> fillMix(Mix__c mix)
	{
		Song__c s = new Song__c(Name='song',Track_Licenses__c =22,Length_m__c = 1.00, Artist__c = 'Michael Jackson');
		insert s;
		List<Track__c> tracks = new List<Track__c>();
		for (Integer i = 0; i < MAX_TRACK_COUNT; i++)
			tracks.add(new Track__c(Mix__c = mix.Id, Song__c = s.Id));
		insert tracks;
		return tracks;
	}
	public static List<Track__c> fillMixWithDifferentSongs(Mix__c mix)
	{
		List<Track__c> tracks = new List<Track__c>();
		for(Song__c s : [SELECT Id FROM Song__c])
			tracks.add(new Track__c(Mix__c = mix.Id, Song__c = s.Id));
		insert tracks;
		return tracks;
	}

}